# Common
common.select=Select
common.save=Save
common.cancel=Cancel
common.update=Update
common.delete=Delete

# Meal
meal.title=Meals
meal.add=Add Meal
meal.create=Create Meal
meal.dateTime=Date/Time
meal.description=Description
meal.calories=Calories
meal.filter.startDate=From date (inclusive)
meal.filter.endDate=To Date (inclusive)
meal.filter.startTime=From Time (inclusive)
meal.filter.endTime=To Time (inclusive)
meal.filter.apply=Filter

# User
user.title=Users
user.name=Name
user.email=Email
user.roles=Roles
user.active=Active
user.registered=Registered

# App
app.login=Login
app.title=Calories Managements
app.home=Home
app.footer=@ 2026 Calories Managements